version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile  # Ruta a tu Dockerfile del backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile  # Asegúrate de tener un Dockerfile para el frontend
    ports:
      - "3000:3000"  # Cambia el puerto según lo que uses para tu frontend
    volumes:
      - ./frontend:/app


