# nixpacks.toml
version = "0.1"

[build]
builder = "python"
commands = [
  "pip install --upgrade pip",
  "pip install -r backend/requirements.txt"
]

[web]
cmd = "cd backend && gunicorn -w 4 -b 0.0.0.0:8000 app:app"
